spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  datasource:
    #    url: jdbc:mariadb:mem:testdb;MODE=MariaDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url : jdbc:mariadb://localhost:3306/product_sales
    username: root
    password: 1q2w3e4r
    driverClassName: org.mariadb.jdbc.Driver